name: Update ratings-summary.json

on:
  repository_dispatch:
    types: [update-ratings-json]

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Write ratings-summary.json
        run: |
          echo '${{ github.event.client_payload.json }}' > ratings-summary.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ratings-summary.json
          git commit -m "Update ratings-summary.json via GitHub Action" || echo "No changes"
          git push
